version: 2.1

jobs:
  deploy:
    docker:
      - image: nitinbhardwaj12/alpine-ssh
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v ubuntu@54.198.43.183 "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
